version: '3'

services:
  api:
    build: .
    container_name: grok-api-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    networks:
      - grok-network
  
  redis:
    image: redis:alpine
    container_name: grok-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - grok-network

volumes:
  redis_data:
    driver: local

networks:
  grok-network:
    driver: bridge